"""make_table4.py -- Table IV (tab:law) and every summary statistic quoted around it, from ONE file.

usage: python make_table4.py grid_final.csv > table4.txt

Reproduces analyze.py's per-instance statistic exactly (rule from the smallest-K row, round() on
the commute branch, sign tests on J(l+-1) - J(l)) so the table and the prose cannot drift apart
again. Prints: (1) LaTeX rows for tab:law, (2) the overall and per-family agreement, (3) the
numbers the "Overall", "Two localised failure families" and "domain of validity" paragraphs use.
"""
import sys, csv, math
from collections import defaultdict
import numpy as np

rows = [r for r in csv.DictReader(open(sys.argv[1]))]
cells = defaultdict(lambda: defaultdict(dict))
for r in rows:
    if float(r["L"]) != 12600.0:
        continue
    cells[(r["layout"], int(r["M"]), float(r["Emax"]))][int(r["seed"])][int(r["K"])] = r


def sign_test(d):
    d = np.asarray(d); n = len(d); s = int((d > 0).sum())
    p = sum(math.comb(n, k) for k in range(max(s, n - s), n + 1)) / 2 ** n * 2 if n else float("nan")
    return s, n, min(p, 1.0)


def fmt_p(p):
    if p != p: return "--"
    if p < 0.001: return "$<$.001"
    if p >= 0.9995: return "1.00"
    return f"{p:.3f}".lstrip("0")


order = {"paper": 0, "ring": 1, "core": 2}
keys = sorted(cells, key=lambda k: (order[k[0]], k[2], k[1]))
per_cell = {}
all_inst = []
for key in keys:
    inst = cells[key]
    A = []; Lw = []; dplus = []; dminus = []; ratio = []; bnd = []; inrng = []
    for seed, byK in sorted(inst.items()):
        Ks = sorted(byK); J = {K: float(byK[K]["J"]) for K in Ks}
        am = min(Ks, key=J.get); r0 = byK[Ks[0]]
        kr = math.floor(float(r0["K_reach_i"])); kc = float(r0["K_commute_i"])
        law = min(kr, kc); li = int(law) if law == kr else int(round(law))
        A.append(am); Lw.append(li); ratio.append(float(r0["rmax_over_rc"])); bnd.append(float(r0["regime_bnd"]))
        inrng.append(Ks[0] <= li <= Ks[-1])
        if li in J and li + 1 in J: dplus.append(J[li + 1] - J[li])
        if li in J and li - 1 in J: dminus.append(J[li - 1] - J[li])
        all_inst.append((key, am, li, Ks[0] <= li <= Ks[-1], am == Ks[-1]))
    A = np.array(A); Lw = np.array(Lw)
    per_cell[key] = dict(n=len(A), am=A.mean(), l=Lw.mean(), ex=np.mean(A == Lw), w1=np.mean(abs(A - Lw) <= 1),
                         sp=sign_test(dplus), sm=sign_test(dminus), ratio=np.mean(ratio), bnd=np.mean(bnd),
                         cens=np.mean([x[4] for x in all_inst if x[0] == key]), inrng=np.mean(inrng))

print("% ---- tab:law rows (generated by make_table4.py; do not edit by hand) ----")
prev = None
for key in keys:
    lay, M, E = key; c = per_cell[key]
    if prev is not None and lay != prev: print("\\midrule")
    prev = lay
    regime = "reach" if c["ratio"] > c["bnd"] else "commute"
    mark = ""
    if lay == "ring" and E == 3e6: mark = "$^{\\dagger}$"
    if lay == "core": mark = "$^{\\ddagger}$"
    rr = f"{c['ratio']:.2f}" if lay == "ring" else f"{c['ratio']:.1f}"
    am_str = (f"$\\ge${c['am']:.2f}" if c['cens'] > 0 else f"{c['am']:.2f}")   # a right-censored instance makes the mean a lower bound
    print(f"{lay} & {M} & {E/1e6:.1f} & {c['n']} & {am_str} & {c['l']:.2f} & {c['ex']:.2f} & {c['w1']:.2f} & "
          f"{c['sp'][0]}/{c['sp'][1]} & {fmt_p(c['sp'][2])} & {c['sm'][0]}/{c['sm'][1]} & {fmt_p(c['sm'][2])} & "
          f"{rr} & {c['bnd']:.1f} & {regime}{mark}\\\\")

ex = np.array([x[1] == x[2] for x in all_inst]); w1 = np.array([abs(x[1] - x[2]) <= 1 for x in all_inst])
inr = np.array([x[3] for x in all_inst]); cens = np.array([x[4] for x in all_inst])
print(f"\n% primary grid: {len(keys)} cells, {len(all_inst)} instances")
print(f"%   all instances:          exact {ex.mean():.3f}  within-one {w1.mean():.3f}")
print(f"%   rule inside sweep ({inr.sum()}): exact {ex[inr].mean():.3f}  within-one {w1[inr].mean():.3f}")
print(f"%   argmin at top of sweep (censored): {cens.sum()} of {len(cens)}")
for fam in ("paper", "ring", "core"):
    m = np.array([x[0][0] == fam for x in all_inst])
    print(f"%   {fam:5s}: exact {ex[m].mean():.3f} within-one {w1[m].mean():.3f}  (n={m.sum()})")
allw = [k for k in keys if per_cell[k]["w1"] == 1.0]
print(f"%   cells with every instance within one: {len(allw)} of {len(keys)}")
bad = [k for k in keys if per_cell[k]["w1"] < 0.9]
m = np.array([x[0] not in bad for x in all_inst])
print(f"%   cells with within-one < 0.9: {bad}")
print(f"%   excluding them: exact {ex[m].mean():.3f} within-one {w1[m].mean():.3f} over {len(keys)-len(bad)} cells")
good = [k for k in keys if k not in bad]
bias = [per_cell[k]["am"] - per_cell[k]["l"] for k in good]
print(f"%   those {len(good)} cells: mean bias {np.mean(bias):+.2f} (relative {np.mean([b/per_cell[k]['l'] for b,k in zip(bias,good)]):+.1%}), "
      f"worst {max(bias, key=abs):+.2f}")

reach = [k for k in keys if k[0] in ("paper", "core")]
rel = np.array([(per_cell[k]["am"] - per_cell[k]["l"]) / per_cell[k]["l"] for k in reach])
rat = np.array([per_cell[k]["ratio"] for k in reach])
print(f"\n% reach-limited cells ({len(reach)}): corr(relative bias, rmax/rc) = {np.corrcoef(rel, rat)[0,1]:.2f}")
for k, a, b in sorted(zip(reach, rat, rel), key=lambda t: t[1]):
    print(f"%   {k[0]:5s} M={k[1]:3d} {k[2]/1e6:.1f}MJ  rmax/rc {a:5.1f}  relative bias {b:+.0%}")
